version: "2"

linters:
  default: all
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
    govet:
      enable-all: true
      disable:
        - fieldalignment
  disable:
    - containedctx
    - cyclop
    - depguard
    - exhaustruct
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - goconst
    - godox
    - mnd
    - nlreturn
    - noctx
    - noinlineerr
    - nonamedreturns
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
