// Code generated by gogram/cmd/gen; DO NOT EDIT.

package gogram

func (ctx *Context) findHandlerOn() handleOn {
	if ctx.update == nil {
		return 0
	}

	switch {
	case ctx.update.Message != nil:
		return handleOnMessage
	case ctx.update.EditedMessage != nil:
		return handleOnEditedMessage
	case ctx.update.ChannelPost != nil:
		return handleOnChannelPost
	case ctx.update.EditedChannelPost != nil:
		return handleOnEditedChannelPost
	case ctx.update.BusinessConnection != nil:
		return handleOnBusinessConnection
	case ctx.update.BusinessMessage != nil:
		return handleOnBusinessMessage
	case ctx.update.EditedBusinessMessage != nil:
		return handleOnEditedBusinessMessage
	case ctx.update.MessageReaction != nil:
		return handleOnMessageReaction
	case ctx.update.InlineQuery != nil:
		return handleOnInlineQuery
	case ctx.update.ChosenInlineResult != nil:
		return handleOnChosenInlineResult
	case ctx.update.CallbackQuery != nil:
		return handleOnCallbackQuery
	case ctx.update.ShippingQuery != nil:
		return handleOnShippingQuery
	case ctx.update.PreCheckoutQuery != nil:
		return handleOnPreCheckoutQuery
	case ctx.update.PurchasedPaidMedia != nil:
		return handleOnPurchasedPaidMedia
	case ctx.update.PollAnswer != nil:
		return handleOnPollAnswer
	case ctx.update.MyChatMember != nil:
		return handleOnMyChatMember
	case ctx.update.ChatMember != nil:
		return handleOnChatMember
	case ctx.update.ChatJoinRequest != nil:
		return handleOnChatJoinRequest
	}

	return 0
}

func (ctx *Context) User() *User {
	if ctx.update == nil {
		return nil
	}

	switch {
	case ctx.update.Message != nil:
		return ctx.update.Message.From
	case ctx.update.EditedMessage != nil:
		return ctx.update.EditedMessage.From
	case ctx.update.ChannelPost != nil:
		return ctx.update.ChannelPost.From
	case ctx.update.EditedChannelPost != nil:
		return ctx.update.EditedChannelPost.From
	case ctx.update.BusinessConnection != nil:
		return &ctx.update.BusinessConnection.User
	case ctx.update.BusinessMessage != nil:
		return ctx.update.BusinessMessage.From
	case ctx.update.EditedBusinessMessage != nil:
		return ctx.update.EditedBusinessMessage.From
	case ctx.update.MessageReaction != nil:
		return ctx.update.MessageReaction.User
	case ctx.update.InlineQuery != nil:
		return &ctx.update.InlineQuery.From
	case ctx.update.ChosenInlineResult != nil:
		return &ctx.update.ChosenInlineResult.From
	case ctx.update.CallbackQuery != nil:
		return &ctx.update.CallbackQuery.From
	case ctx.update.ShippingQuery != nil:
		return &ctx.update.ShippingQuery.From
	case ctx.update.PreCheckoutQuery != nil:
		return &ctx.update.PreCheckoutQuery.From
	case ctx.update.PurchasedPaidMedia != nil:
		return &ctx.update.PurchasedPaidMedia.From
	case ctx.update.PollAnswer != nil:
		return ctx.update.PollAnswer.User
	case ctx.update.MyChatMember != nil:
		return &ctx.update.MyChatMember.From
	case ctx.update.ChatMember != nil:
		return &ctx.update.ChatMember.From
	case ctx.update.ChatJoinRequest != nil:
		return &ctx.update.ChatJoinRequest.From
	}

	return nil
}

func (ctx *Context) ChatID() string {
	if ctx.update == nil {
		return ""
	}

	switch {
	case ctx.update.Message != nil:
		return ctx.update.Message.Chat.Identifier()
	case ctx.update.EditedMessage != nil:
		return ctx.update.EditedMessage.Chat.Identifier()
	case ctx.update.ChannelPost != nil:
		return ctx.update.ChannelPost.Chat.Identifier()
	case ctx.update.EditedChannelPost != nil:
		return ctx.update.EditedChannelPost.Chat.Identifier()
	case ctx.update.BusinessMessage != nil:
		return ctx.update.BusinessMessage.Chat.Identifier()
	case ctx.update.EditedBusinessMessage != nil:
		return ctx.update.EditedBusinessMessage.Chat.Identifier()
	case ctx.update.DeletedBusinessMessages != nil:
		return ctx.update.DeletedBusinessMessages.Chat.Identifier()
	case ctx.update.MessageReaction != nil:
		return ctx.update.MessageReaction.Chat.Identifier()
	case ctx.update.MessageReactionCount != nil:
		return ctx.update.MessageReactionCount.Chat.Identifier()
	case ctx.update.MyChatMember != nil:
		return ctx.update.MyChatMember.Chat.Identifier()
	case ctx.update.ChatMember != nil:
		return ctx.update.ChatMember.Chat.Identifier()
	case ctx.update.ChatJoinRequest != nil:
		return ctx.update.ChatJoinRequest.Chat.Identifier()
	case ctx.update.ChatBoost != nil:
		return ctx.update.ChatBoost.Chat.Identifier()
	case ctx.update.RemovedChatBoost != nil:
		return ctx.update.RemovedChatBoost.Chat.Identifier()
	}

	return ""
}

func (ctx *Context) Message() *Message {
	if ctx.update == nil {
		return nil
	}

	switch {
	case ctx.update.Message != nil:
		return ctx.update.Message
	case ctx.update.EditedMessage != nil:
		return ctx.update.EditedMessage
	case ctx.update.ChannelPost != nil:
		return ctx.update.ChannelPost
	case ctx.update.EditedChannelPost != nil:
		return ctx.update.EditedChannelPost
	case ctx.update.BusinessMessage != nil:
		return ctx.update.BusinessMessage
	case ctx.update.EditedBusinessMessage != nil:
		return ctx.update.EditedBusinessMessage
	}

	return nil
}

func (ctx *Context) Text() string {
	m := ctx.Message()
	if m == nil {
		return ""
	}

	return m.Text
}

func (ctx *Context) Payload() string {
	return ExtractPayload(ctx.Text())
}

func (ctx *Context) AddStickerToSet(
	userID int64,
	name string,
	sticker InputSticker,
	opts ...AddStickerToSetOption,
) error {
	params := &AddStickerToSetParams{
		UserID:  userID,
		Name:    name,
		Sticker: sticker,
	}

	params.Option(opts...)

	_, err := ctx.client.AddStickerToSet(params)

	return err
}

func (ctx *Context) AnswerCallbackQuery(

	opts ...AnswerCallbackQueryOption,
) error {
	params := &AnswerCallbackQueryParams{}

	params.CallbackQueryID = func(ctx *Context) string {
		if ctx.update == nil {
			return ""
		}

		if ctx.update.CallbackQuery == nil {
			return ""
		}

		return ctx.update.CallbackQuery.ID
	}(ctx)

	params.Option(opts...)

	_, err := ctx.client.AnswerCallbackQuery(params)

	return err
}

func (ctx *Context) AnswerInlineQuery(
	inlineQueryID string,
	results []InlineQueryResult,
	opts ...AnswerInlineQueryOption,
) error {
	params := &AnswerInlineQueryParams{
		InlineQueryID: inlineQueryID,
		Results:       results,
	}

	params.Option(opts...)

	_, err := ctx.client.AnswerInlineQuery(params)

	return err
}

func (ctx *Context) AnswerPreCheckoutQuery(
	preCheckoutQueryID string,
	ok bool,
	opts ...AnswerPreCheckoutQueryOption,
) error {
	params := &AnswerPreCheckoutQueryParams{
		PreCheckoutQueryID: preCheckoutQueryID,
		Ok:                 ok,
	}

	params.Option(opts...)

	_, err := ctx.client.AnswerPreCheckoutQuery(params)

	return err
}

func (ctx *Context) AnswerShippingQuery(
	shippingQueryID string,
	ok bool,
	opts ...AnswerShippingQueryOption,
) error {
	params := &AnswerShippingQueryParams{
		ShippingQueryID: shippingQueryID,
		Ok:              ok,
	}

	params.Option(opts...)

	_, err := ctx.client.AnswerShippingQuery(params)

	return err
}

func (ctx *Context) AnswerWebAppQuery(
	webAppQueryID string,
	result InlineQueryResult,
	opts ...AnswerWebAppQueryOption,
) error {
	params := &AnswerWebAppQueryParams{
		WebAppQueryID: webAppQueryID,
		Result:        result,
	}

	params.Option(opts...)

	_, err := ctx.client.AnswerWebAppQuery(params)

	return err
}

func (ctx *Context) ApproveChatJoinRequest(

	userID int64,
	opts ...ApproveChatJoinRequestOption,
) error {
	params := &ApproveChatJoinRequestParams{

		UserID: userID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.ApproveChatJoinRequest(params)

	return err
}

func (ctx *Context) ApproveSuggestedPost(
	chatID int64,
	messageID int64,
	opts ...ApproveSuggestedPostOption,
) error {
	params := &ApproveSuggestedPostParams{
		ChatID:    chatID,
		MessageID: messageID,
	}

	params.Option(opts...)

	_, err := ctx.client.ApproveSuggestedPost(params)

	return err
}

func (ctx *Context) BanChatMember(

	userID int64,
	opts ...BanChatMemberOption,
) error {
	params := &BanChatMemberParams{

		UserID: userID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.BanChatMember(params)

	return err
}

func (ctx *Context) BanChatSenderChat(

	senderChatID int64,
	opts ...BanChatSenderChatOption,
) error {
	params := &BanChatSenderChatParams{

		SenderChatID: senderChatID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.BanChatSenderChat(params)

	return err
}

func (ctx *Context) Close(
	opts ...CloseOption,
) error {
	params := &CloseParams{}

	params.Option(opts...)

	_, err := ctx.client.Close(params)

	return err
}

func (ctx *Context) CloseForumTopic(

	messageThreadID int64,
	opts ...CloseForumTopicOption,
) error {
	params := &CloseForumTopicParams{

		MessageThreadID: messageThreadID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.CloseForumTopic(params)

	return err
}

func (ctx *Context) CloseGeneralForumTopic(

	opts ...CloseGeneralForumTopicOption,
) error {
	params := &CloseGeneralForumTopicParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.CloseGeneralForumTopic(params)

	return err
}

func (ctx *Context) ConvertGiftToStars(
	businessConnectionID string,
	ownedGiftID string,
	opts ...ConvertGiftToStarsOption,
) error {
	params := &ConvertGiftToStarsParams{
		BusinessConnectionID: businessConnectionID,
		OwnedGiftID:          ownedGiftID,
	}

	params.Option(opts...)

	_, err := ctx.client.ConvertGiftToStars(params)

	return err
}

func (ctx *Context) CopyMessage(

	fromChatID string,
	messageID int64,
	opts ...CopyMessageOption,
) error {
	params := &CopyMessageParams{

		FromChatID: fromChatID,
		MessageID:  messageID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.CaptionEntities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.CopyMessage(params)

	return err
}

func (ctx *Context) CopyMessages(

	fromChatID string,
	messageIDs []int64,
	opts ...CopyMessagesOption,
) error {
	params := &CopyMessagesParams{

		FromChatID: fromChatID,
		MessageIDs: messageIDs,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.CopyMessages(params)

	return err
}

func (ctx *Context) CreateChatInviteLink(

	opts ...CreateChatInviteLinkOption,
) error {
	params := &CreateChatInviteLinkParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.CreateChatInviteLink(params)

	return err
}

func (ctx *Context) CreateChatSubscriptionInviteLink(

	subscriptionPeriod int64,
	subscriptionPrice int64,
	opts ...CreateChatSubscriptionInviteLinkOption,
) error {
	params := &CreateChatSubscriptionInviteLinkParams{

		SubscriptionPeriod: subscriptionPeriod,
		SubscriptionPrice:  subscriptionPrice,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.CreateChatSubscriptionInviteLink(params)

	return err
}

func (ctx *Context) CreateForumTopic(

	name string,
	opts ...CreateForumTopicOption,
) error {
	params := &CreateForumTopicParams{

		Name: name,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.CreateForumTopic(params)

	return err
}

func (ctx *Context) CreateInvoiceLink(
	title string,
	description string,
	payload string,
	currency string,
	prices []LabeledPrice,
	opts ...CreateInvoiceLinkOption,
) error {
	params := &CreateInvoiceLinkParams{
		Title:       title,
		Description: description,
		Payload:     payload,
		Currency:    currency,
		Prices:      prices,
	}

	params.Option(opts...)

	_, err := ctx.client.CreateInvoiceLink(params)

	return err
}

func (ctx *Context) CreateNewStickerSet(
	userID int64,
	name string,
	title string,
	stickers []InputSticker,
	opts ...CreateNewStickerSetOption,
) error {
	params := &CreateNewStickerSetParams{
		UserID:   userID,
		Name:     name,
		Title:    title,
		Stickers: stickers,
	}

	params.Option(opts...)

	_, err := ctx.client.CreateNewStickerSet(params)

	return err
}

func (ctx *Context) DeclineChatJoinRequest(

	userID int64,
	opts ...DeclineChatJoinRequestOption,
) error {
	params := &DeclineChatJoinRequestParams{

		UserID: userID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.DeclineChatJoinRequest(params)

	return err
}

func (ctx *Context) DeclineSuggestedPost(
	chatID int64,
	messageID int64,
	opts ...DeclineSuggestedPostOption,
) error {
	params := &DeclineSuggestedPostParams{
		ChatID:    chatID,
		MessageID: messageID,
	}

	params.Option(opts...)

	_, err := ctx.client.DeclineSuggestedPost(params)

	return err
}

func (ctx *Context) DeleteBusinessMessages(
	businessConnectionID string,
	messageIDs []int64,
	opts ...DeleteBusinessMessagesOption,
) error {
	params := &DeleteBusinessMessagesParams{
		BusinessConnectionID: businessConnectionID,
		MessageIDs:           messageIDs,
	}

	params.Option(opts...)

	_, err := ctx.client.DeleteBusinessMessages(params)

	return err
}

func (ctx *Context) DeleteChatPhoto(

	opts ...DeleteChatPhotoOption,
) error {
	params := &DeleteChatPhotoParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.DeleteChatPhoto(params)

	return err
}

func (ctx *Context) DeleteChatStickerSet(

	opts ...DeleteChatStickerSetOption,
) error {
	params := &DeleteChatStickerSetParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.DeleteChatStickerSet(params)

	return err
}

func (ctx *Context) DeleteForumTopic(

	messageThreadID int64,
	opts ...DeleteForumTopicOption,
) error {
	params := &DeleteForumTopicParams{

		MessageThreadID: messageThreadID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.DeleteForumTopic(params)

	return err
}

func (ctx *Context) DeleteMessage(

	messageID int64,
	opts ...DeleteMessageOption,
) error {
	params := &DeleteMessageParams{

		MessageID: messageID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.DeleteMessage(params)

	return err
}

func (ctx *Context) DeleteMessages(

	messageIDs []int64,
	opts ...DeleteMessagesOption,
) error {
	params := &DeleteMessagesParams{

		MessageIDs: messageIDs,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.DeleteMessages(params)

	return err
}

func (ctx *Context) DeleteMyCommands(
	opts ...DeleteMyCommandsOption,
) error {
	params := &DeleteMyCommandsParams{}

	params.Option(opts...)

	_, err := ctx.client.DeleteMyCommands(params)

	return err
}

func (ctx *Context) DeleteStickerFromSet(
	sticker string,
	opts ...DeleteStickerFromSetOption,
) error {
	params := &DeleteStickerFromSetParams{
		Sticker: sticker,
	}

	params.Option(opts...)

	_, err := ctx.client.DeleteStickerFromSet(params)

	return err
}

func (ctx *Context) DeleteStickerSet(
	name string,
	opts ...DeleteStickerSetOption,
) error {
	params := &DeleteStickerSetParams{
		Name: name,
	}

	params.Option(opts...)

	_, err := ctx.client.DeleteStickerSet(params)

	return err
}

func (ctx *Context) DeleteStory(
	businessConnectionID string,
	storyID int64,
	opts ...DeleteStoryOption,
) error {
	params := &DeleteStoryParams{
		BusinessConnectionID: businessConnectionID,
		StoryID:              storyID,
	}

	params.Option(opts...)

	_, err := ctx.client.DeleteStory(params)

	return err
}

func (ctx *Context) DeleteWebhook(
	opts ...DeleteWebhookOption,
) error {
	params := &DeleteWebhookParams{}

	params.Option(opts...)

	_, err := ctx.client.DeleteWebhook(params)

	return err
}

func (ctx *Context) EditChatInviteLink(

	inviteLink string,
	opts ...EditChatInviteLinkOption,
) error {
	params := &EditChatInviteLinkParams{

		InviteLink: inviteLink,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.EditChatInviteLink(params)

	return err
}

func (ctx *Context) EditChatSubscriptionInviteLink(

	inviteLink string,
	opts ...EditChatSubscriptionInviteLinkOption,
) error {
	params := &EditChatSubscriptionInviteLinkParams{

		InviteLink: inviteLink,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.EditChatSubscriptionInviteLink(params)

	return err
}

func (ctx *Context) EditForumTopic(

	messageThreadID int64,
	opts ...EditForumTopicOption,
) error {
	params := &EditForumTopicParams{

		MessageThreadID: messageThreadID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.EditForumTopic(params)

	return err
}

func (ctx *Context) EditGeneralForumTopic(

	name string,
	opts ...EditGeneralForumTopicOption,
) error {
	params := &EditGeneralForumTopicParams{

		Name: name,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.EditGeneralForumTopic(params)

	return err
}

func (ctx *Context) EditMessageCaption(

	opts ...EditMessageCaptionOption,
) error {
	params := &EditMessageCaptionParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.CaptionEntities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.EditMessageCaption(params)

	return err
}

func (ctx *Context) EditMessageChecklist(
	businessConnectionID string,
	chatID int64,
	messageID int64,
	checklist InputChecklist,
	opts ...EditMessageChecklistOption,
) error {
	params := &EditMessageChecklistParams{
		BusinessConnectionID: businessConnectionID,
		ChatID:               chatID,
		MessageID:            messageID,
		Checklist:            checklist,
	}

	params.Option(opts...)

	_, err := ctx.client.EditMessageChecklist(params)

	return err
}

func (ctx *Context) EditMessageLiveLocation(

	latitude float64,
	longitude float64,
	opts ...EditMessageLiveLocationOption,
) error {
	params := &EditMessageLiveLocationParams{

		Latitude:  latitude,
		Longitude: longitude,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.EditMessageLiveLocation(params)

	return err
}

func (ctx *Context) EditMessageMedia(

	media InputMedia,
	opts ...EditMessageMediaOption,
) error {
	params := &EditMessageMediaParams{

		Media: media,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		defaultParseModeToInputMedia(&params.Media, defaultParseMode)
	}

	_, err := ctx.client.EditMessageMedia(params)

	return err
}

func (ctx *Context) EditMessageReplyMarkup(

	opts ...EditMessageReplyMarkupOption,
) error {
	params := &EditMessageReplyMarkupParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.EditMessageReplyMarkup(params)

	return err
}

func (ctx *Context) EditMessageText(

	text string,
	opts ...EditMessageTextOption,
) error {
	params := &EditMessageTextParams{

		Text: text,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.Entities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.EditMessageText(params)

	return err
}

func (ctx *Context) EditStory(
	businessConnectionID string,
	storyID int64,
	content InputStoryContent,
	opts ...EditStoryOption,
) error {
	params := &EditStoryParams{
		BusinessConnectionID: businessConnectionID,
		StoryID:              storyID,
		Content:              content,
	}

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.CaptionEntities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.EditStory(params)

	return err
}

func (ctx *Context) EditUserStarSubscription(
	userID int64,
	telegramPaymentChargeID string,
	isCanceled bool,
	opts ...EditUserStarSubscriptionOption,
) error {
	params := &EditUserStarSubscriptionParams{
		UserID:                  userID,
		TelegramPaymentChargeID: telegramPaymentChargeID,
		IsCanceled:              isCanceled,
	}

	params.Option(opts...)

	_, err := ctx.client.EditUserStarSubscription(params)

	return err
}

func (ctx *Context) ExportChatInviteLink(

	opts ...ExportChatInviteLinkOption,
) error {
	params := &ExportChatInviteLinkParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.ExportChatInviteLink(params)

	return err
}

func (ctx *Context) ForwardMessage(

	fromChatID string,
	messageID int64,
	opts ...ForwardMessageOption,
) error {
	params := &ForwardMessageParams{

		FromChatID: fromChatID,
		MessageID:  messageID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.ForwardMessage(params)

	return err
}

func (ctx *Context) ForwardMessages(

	fromChatID string,
	messageIDs []int64,
	opts ...ForwardMessagesOption,
) error {
	params := &ForwardMessagesParams{

		FromChatID: fromChatID,
		MessageIDs: messageIDs,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.ForwardMessages(params)

	return err
}

func (ctx *Context) GetAvailableGifts(
	opts ...GetAvailableGiftsOption,
) error {
	params := &GetAvailableGiftsParams{}

	params.Option(opts...)

	_, err := ctx.client.GetAvailableGifts(params)

	return err
}

func (ctx *Context) GetBusinessAccountGifts(
	businessConnectionID string,
	opts ...GetBusinessAccountGiftsOption,
) error {
	params := &GetBusinessAccountGiftsParams{
		BusinessConnectionID: businessConnectionID,
	}

	params.Option(opts...)

	_, err := ctx.client.GetBusinessAccountGifts(params)

	return err
}

func (ctx *Context) GetBusinessAccountStarBalance(
	businessConnectionID string,
	opts ...GetBusinessAccountStarBalanceOption,
) error {
	params := &GetBusinessAccountStarBalanceParams{
		BusinessConnectionID: businessConnectionID,
	}

	params.Option(opts...)

	_, err := ctx.client.GetBusinessAccountStarBalance(params)

	return err
}

func (ctx *Context) GetBusinessConnection(
	businessConnectionID string,
	opts ...GetBusinessConnectionOption,
) error {
	params := &GetBusinessConnectionParams{
		BusinessConnectionID: businessConnectionID,
	}

	params.Option(opts...)

	_, err := ctx.client.GetBusinessConnection(params)

	return err
}

func (ctx *Context) GetChat(

	opts ...GetChatOption,
) error {
	params := &GetChatParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.GetChat(params)

	return err
}

func (ctx *Context) GetChatAdministrators(

	opts ...GetChatAdministratorsOption,
) error {
	params := &GetChatAdministratorsParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.GetChatAdministrators(params)

	return err
}

func (ctx *Context) GetChatGifts(

	opts ...GetChatGiftsOption,
) error {
	params := &GetChatGiftsParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.GetChatGifts(params)

	return err
}

func (ctx *Context) GetChatMember(

	userID int64,
	opts ...GetChatMemberOption,
) error {
	params := &GetChatMemberParams{

		UserID: userID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.GetChatMember(params)

	return err
}

func (ctx *Context) GetChatMemberCount(

	opts ...GetChatMemberCountOption,
) error {
	params := &GetChatMemberCountParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.GetChatMemberCount(params)

	return err
}

func (ctx *Context) GetChatMenuButton(
	opts ...GetChatMenuButtonOption,
) error {
	params := &GetChatMenuButtonParams{}

	params.Option(opts...)

	_, err := ctx.client.GetChatMenuButton(params)

	return err
}

func (ctx *Context) GetCustomEmojiStickers(
	customEmojiIDs []string,
	opts ...GetCustomEmojiStickersOption,
) error {
	params := &GetCustomEmojiStickersParams{
		CustomEmojiIDs: customEmojiIDs,
	}

	params.Option(opts...)

	_, err := ctx.client.GetCustomEmojiStickers(params)

	return err
}

func (ctx *Context) GetFile(
	fileID string,
	opts ...GetFileOption,
) error {
	params := &GetFileParams{
		FileID: fileID,
	}

	params.Option(opts...)

	_, err := ctx.client.GetFile(params)

	return err
}

func (ctx *Context) GetForumTopicIconStickers(
	opts ...GetForumTopicIconStickersOption,
) error {
	params := &GetForumTopicIconStickersParams{}

	params.Option(opts...)

	_, err := ctx.client.GetForumTopicIconStickers(params)

	return err
}

func (ctx *Context) GetGameHighScores(
	userID int64,
	opts ...GetGameHighScoresOption,
) error {
	params := &GetGameHighScoresParams{
		UserID: userID,
	}

	params.Option(opts...)

	_, err := ctx.client.GetGameHighScores(params)

	return err
}

func (ctx *Context) GetMe(
	opts ...GetMeOption,
) error {
	params := &GetMeParams{}

	params.Option(opts...)

	_, err := ctx.client.GetMe(params)

	return err
}

func (ctx *Context) GetMyCommands(
	opts ...GetMyCommandsOption,
) error {
	params := &GetMyCommandsParams{}

	params.Option(opts...)

	_, err := ctx.client.GetMyCommands(params)

	return err
}

func (ctx *Context) GetMyDefaultAdministratorRights(
	opts ...GetMyDefaultAdministratorRightsOption,
) error {
	params := &GetMyDefaultAdministratorRightsParams{}

	params.Option(opts...)

	_, err := ctx.client.GetMyDefaultAdministratorRights(params)

	return err
}

func (ctx *Context) GetMyDescription(
	opts ...GetMyDescriptionOption,
) error {
	params := &GetMyDescriptionParams{}

	params.Option(opts...)

	_, err := ctx.client.GetMyDescription(params)

	return err
}

func (ctx *Context) GetMyName(
	opts ...GetMyNameOption,
) error {
	params := &GetMyNameParams{}

	params.Option(opts...)

	_, err := ctx.client.GetMyName(params)

	return err
}

func (ctx *Context) GetMyShortDescription(
	opts ...GetMyShortDescriptionOption,
) error {
	params := &GetMyShortDescriptionParams{}

	params.Option(opts...)

	_, err := ctx.client.GetMyShortDescription(params)

	return err
}

func (ctx *Context) GetMyStarBalance(
	opts ...GetMyStarBalanceOption,
) error {
	params := &GetMyStarBalanceParams{}

	params.Option(opts...)

	_, err := ctx.client.GetMyStarBalance(params)

	return err
}

func (ctx *Context) GetStarTransactions(
	opts ...GetStarTransactionsOption,
) error {
	params := &GetStarTransactionsParams{}

	params.Option(opts...)

	_, err := ctx.client.GetStarTransactions(params)

	return err
}

func (ctx *Context) GetStickerSet(
	name string,
	opts ...GetStickerSetOption,
) error {
	params := &GetStickerSetParams{
		Name: name,
	}

	params.Option(opts...)

	_, err := ctx.client.GetStickerSet(params)

	return err
}

func (ctx *Context) GetUpdates(
	opts ...GetUpdatesOption,
) error {
	params := &GetUpdatesParams{}

	params.Option(opts...)

	_, err := ctx.client.GetUpdates(params)

	return err
}

func (ctx *Context) GetUserChatBoosts(

	userID int64,
	opts ...GetUserChatBoostsOption,
) error {
	params := &GetUserChatBoostsParams{

		UserID: userID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.GetUserChatBoosts(params)

	return err
}

func (ctx *Context) GetUserGifts(
	userID int64,
	opts ...GetUserGiftsOption,
) error {
	params := &GetUserGiftsParams{
		UserID: userID,
	}

	params.Option(opts...)

	_, err := ctx.client.GetUserGifts(params)

	return err
}

func (ctx *Context) GetUserProfileAudios(
	userID int64,
	opts ...GetUserProfileAudiosOption,
) error {
	params := &GetUserProfileAudiosParams{
		UserID: userID,
	}

	params.Option(opts...)

	_, err := ctx.client.GetUserProfileAudios(params)

	return err
}

func (ctx *Context) GetUserProfilePhotos(
	userID int64,
	opts ...GetUserProfilePhotosOption,
) error {
	params := &GetUserProfilePhotosParams{
		UserID: userID,
	}

	params.Option(opts...)

	_, err := ctx.client.GetUserProfilePhotos(params)

	return err
}

func (ctx *Context) GetWebhookInfo(
	opts ...GetWebhookInfoOption,
) error {
	params := &GetWebhookInfoParams{}

	params.Option(opts...)

	_, err := ctx.client.GetWebhookInfo(params)

	return err
}

func (ctx *Context) GiftPremiumSubscription(
	userID int64,
	monthCount int64,
	starCount int64,
	opts ...GiftPremiumSubscriptionOption,
) error {
	params := &GiftPremiumSubscriptionParams{
		UserID:     userID,
		MonthCount: monthCount,
		StarCount:  starCount,
	}

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
	}

	_, err := ctx.client.GiftPremiumSubscription(params)

	return err
}

func (ctx *Context) HideGeneralForumTopic(

	opts ...HideGeneralForumTopicOption,
) error {
	params := &HideGeneralForumTopicParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.HideGeneralForumTopic(params)

	return err
}

func (ctx *Context) LeaveChat(

	opts ...LeaveChatOption,
) error {
	params := &LeaveChatParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.LeaveChat(params)

	return err
}

func (ctx *Context) LogOut(
	opts ...LogOutOption,
) error {
	params := &LogOutParams{}

	params.Option(opts...)

	_, err := ctx.client.LogOut(params)

	return err
}

func (ctx *Context) PinChatMessage(

	messageID int64,
	opts ...PinChatMessageOption,
) error {
	params := &PinChatMessageParams{

		MessageID: messageID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.PinChatMessage(params)

	return err
}

func (ctx *Context) PostStory(
	businessConnectionID string,
	content InputStoryContent,
	activePeriod int64,
	opts ...PostStoryOption,
) error {
	params := &PostStoryParams{
		BusinessConnectionID: businessConnectionID,
		Content:              content,
		ActivePeriod:         activePeriod,
	}

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.CaptionEntities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.PostStory(params)

	return err
}

func (ctx *Context) PromoteChatMember(

	userID int64,
	opts ...PromoteChatMemberOption,
) error {
	params := &PromoteChatMemberParams{

		UserID: userID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.PromoteChatMember(params)

	return err
}

func (ctx *Context) ReadBusinessMessage(
	businessConnectionID string,
	chatID int64,
	messageID int64,
	opts ...ReadBusinessMessageOption,
) error {
	params := &ReadBusinessMessageParams{
		BusinessConnectionID: businessConnectionID,
		ChatID:               chatID,
		MessageID:            messageID,
	}

	params.Option(opts...)

	_, err := ctx.client.ReadBusinessMessage(params)

	return err
}

func (ctx *Context) RefundStarPayment(
	userID int64,
	telegramPaymentChargeID string,
	opts ...RefundStarPaymentOption,
) error {
	params := &RefundStarPaymentParams{
		UserID:                  userID,
		TelegramPaymentChargeID: telegramPaymentChargeID,
	}

	params.Option(opts...)

	_, err := ctx.client.RefundStarPayment(params)

	return err
}

func (ctx *Context) RemoveBusinessAccountProfilePhoto(
	businessConnectionID string,
	opts ...RemoveBusinessAccountProfilePhotoOption,
) error {
	params := &RemoveBusinessAccountProfilePhotoParams{
		BusinessConnectionID: businessConnectionID,
	}

	params.Option(opts...)

	_, err := ctx.client.RemoveBusinessAccountProfilePhoto(params)

	return err
}

func (ctx *Context) RemoveChatVerification(

	opts ...RemoveChatVerificationOption,
) error {
	params := &RemoveChatVerificationParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.RemoveChatVerification(params)

	return err
}

func (ctx *Context) RemoveMyProfilePhoto(
	opts ...RemoveMyProfilePhotoOption,
) error {
	params := &RemoveMyProfilePhotoParams{}

	params.Option(opts...)

	_, err := ctx.client.RemoveMyProfilePhoto(params)

	return err
}

func (ctx *Context) RemoveUserVerification(
	userID int64,
	opts ...RemoveUserVerificationOption,
) error {
	params := &RemoveUserVerificationParams{
		UserID: userID,
	}

	params.Option(opts...)

	_, err := ctx.client.RemoveUserVerification(params)

	return err
}

func (ctx *Context) ReopenForumTopic(

	messageThreadID int64,
	opts ...ReopenForumTopicOption,
) error {
	params := &ReopenForumTopicParams{

		MessageThreadID: messageThreadID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.ReopenForumTopic(params)

	return err
}

func (ctx *Context) ReopenGeneralForumTopic(

	opts ...ReopenGeneralForumTopicOption,
) error {
	params := &ReopenGeneralForumTopicParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.ReopenGeneralForumTopic(params)

	return err
}

func (ctx *Context) ReplaceStickerInSet(
	userID int64,
	name string,
	oldSticker string,
	sticker InputSticker,
	opts ...ReplaceStickerInSetOption,
) error {
	params := &ReplaceStickerInSetParams{
		UserID:     userID,
		Name:       name,
		OldSticker: oldSticker,
		Sticker:    sticker,
	}

	params.Option(opts...)

	_, err := ctx.client.ReplaceStickerInSet(params)

	return err
}

func (ctx *Context) RepostStory(
	businessConnectionID string,
	fromChatID int64,
	fromStoryID int64,
	activePeriod int64,
	opts ...RepostStoryOption,
) error {
	params := &RepostStoryParams{
		BusinessConnectionID: businessConnectionID,
		FromChatID:           fromChatID,
		FromStoryID:          fromStoryID,
		ActivePeriod:         activePeriod,
	}

	params.Option(opts...)

	_, err := ctx.client.RepostStory(params)

	return err
}

func (ctx *Context) RestrictChatMember(

	userID int64,
	permissions ChatPermissions,
	opts ...RestrictChatMemberOption,
) error {
	params := &RestrictChatMemberParams{

		UserID:      userID,
		Permissions: permissions,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.RestrictChatMember(params)

	return err
}

func (ctx *Context) RevokeChatInviteLink(

	inviteLink string,
	opts ...RevokeChatInviteLinkOption,
) error {
	params := &RevokeChatInviteLinkParams{

		InviteLink: inviteLink,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.RevokeChatInviteLink(params)

	return err
}

func (ctx *Context) SavePreparedInlineMessage(
	userID int64,
	result InlineQueryResult,
	opts ...SavePreparedInlineMessageOption,
) error {
	params := &SavePreparedInlineMessageParams{
		UserID: userID,
		Result: result,
	}

	params.Option(opts...)

	_, err := ctx.client.SavePreparedInlineMessage(params)

	return err
}

func (ctx *Context) SendAnimation(

	animation InputFile,
	opts ...SendAnimationOption,
) error {
	params := &SendAnimationParams{

		Animation: animation,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.CaptionEntities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.SendAnimation(params)

	return err
}

func (ctx *Context) SendAudio(

	audio InputFile,
	opts ...SendAudioOption,
) error {
	params := &SendAudioParams{

		Audio: audio,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.CaptionEntities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.SendAudio(params)

	return err
}

func (ctx *Context) SendChatAction(

	action string,
	opts ...SendChatActionOption,
) error {
	params := &SendChatActionParams{

		Action: action,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SendChatAction(params)

	return err
}

func (ctx *Context) SendChecklist(
	businessConnectionID string,
	chatID int64,
	checklist InputChecklist,
	opts ...SendChecklistOption,
) error {
	params := &SendChecklistParams{
		BusinessConnectionID: businessConnectionID,
		ChatID:               chatID,
		Checklist:            checklist,
	}

	params.Option(opts...)

	_, err := ctx.client.SendChecklist(params)

	return err
}

func (ctx *Context) SendContact(

	phoneNumber string,
	firstName string,
	opts ...SendContactOption,
) error {
	params := &SendContactParams{

		PhoneNumber: phoneNumber,
		FirstName:   firstName,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SendContact(params)

	return err
}

func (ctx *Context) SendDice(

	opts ...SendDiceOption,
) error {
	params := &SendDiceParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SendDice(params)

	return err
}

func (ctx *Context) SendDocument(

	document InputFile,
	opts ...SendDocumentOption,
) error {
	params := &SendDocumentParams{

		Document: document,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.CaptionEntities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.SendDocument(params)

	return err
}

func (ctx *Context) SendGame(
	chatID int64,
	gameShortName string,
	opts ...SendGameOption,
) error {
	params := &SendGameParams{
		ChatID:        chatID,
		GameShortName: gameShortName,
	}

	params.Option(opts...)

	_, err := ctx.client.SendGame(params)

	return err
}

func (ctx *Context) SendGift(

	giftID string,
	opts ...SendGiftOption,
) error {
	params := &SendGiftParams{

		GiftID: giftID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
	}

	_, err := ctx.client.SendGift(params)

	return err
}

func (ctx *Context) SendInvoice(

	title string,
	description string,
	payload string,
	currency string,
	prices []LabeledPrice,
	opts ...SendInvoiceOption,
) error {
	params := &SendInvoiceParams{

		Title:       title,
		Description: description,
		Payload:     payload,
		Currency:    currency,
		Prices:      prices,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SendInvoice(params)

	return err
}

func (ctx *Context) SendLocation(

	latitude float64,
	longitude float64,
	opts ...SendLocationOption,
) error {
	params := &SendLocationParams{

		Latitude:  latitude,
		Longitude: longitude,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SendLocation(params)

	return err
}

func (ctx *Context) SendMediaGroup(

	media []InputMedia,
	opts ...SendMediaGroupOption,
) error {
	params := &SendMediaGroupParams{

		Media: media,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		for i := range params.Media {
			defaultParseModeToInputMedia(&media[i], defaultParseMode)
		}
	}

	_, err := ctx.client.SendMediaGroup(params)

	return err
}

func (ctx *Context) SendMessage(

	text string,
	opts ...SendMessageOption,
) error {
	params := &SendMessageParams{

		Text: text,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.Entities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.SendMessage(params)

	return err
}

func (ctx *Context) SendMessageDraft(
	chatID int64,
	draftID int64,
	text string,
	opts ...SendMessageDraftOption,
) error {
	params := &SendMessageDraftParams{
		ChatID:  chatID,
		DraftID: draftID,
		Text:    text,
	}

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.Entities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.SendMessageDraft(params)

	return err
}

func (ctx *Context) SendPaidMedia(

	starCount int64,
	media []InputPaidMedia,
	opts ...SendPaidMediaOption,
) error {
	params := &SendPaidMediaParams{

		StarCount: starCount,
		Media:     media,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.CaptionEntities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.SendPaidMedia(params)

	return err
}

func (ctx *Context) SendPhoto(

	photo InputFile,
	opts ...SendPhotoOption,
) error {
	params := &SendPhotoParams{

		Photo: photo,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.CaptionEntities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.SendPhoto(params)

	return err
}

func (ctx *Context) SendPoll(

	question string,
	options []InputPollOption,
	opts ...SendPollOption,
) error {
	params := &SendPollParams{

		Question: question,
		Options:  options,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
	}

	_, err := ctx.client.SendPoll(params)

	return err
}

func (ctx *Context) SendSticker(

	sticker InputFile,
	opts ...SendStickerOption,
) error {
	params := &SendStickerParams{

		Sticker: sticker,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SendSticker(params)

	return err
}

func (ctx *Context) SendVenue(

	latitude float64,
	longitude float64,
	title string,
	address string,
	opts ...SendVenueOption,
) error {
	params := &SendVenueParams{

		Latitude:  latitude,
		Longitude: longitude,
		Title:     title,
		Address:   address,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SendVenue(params)

	return err
}

func (ctx *Context) SendVideo(

	video InputFile,
	opts ...SendVideoOption,
) error {
	params := &SendVideoParams{

		Video: video,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.CaptionEntities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.SendVideo(params)

	return err
}

func (ctx *Context) SendVideoNote(

	videoNote InputFile,
	opts ...SendVideoNoteOption,
) error {
	params := &SendVideoNoteParams{

		VideoNote: videoNote,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SendVideoNote(params)

	return err
}

func (ctx *Context) SendVoice(

	voice InputFile,
	opts ...SendVoiceOption,
) error {
	params := &SendVoiceParams{

		Voice: voice,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	if defaultParseMode := ctx.client.defaultParseMode; defaultParseMode != "" {
		if params.ParseMode == "" && len(params.CaptionEntities) == 0 {
			params.ParseMode = defaultParseMode
		}
	}

	_, err := ctx.client.SendVoice(params)

	return err
}

func (ctx *Context) SetBusinessAccountBio(
	businessConnectionID string,
	opts ...SetBusinessAccountBioOption,
) error {
	params := &SetBusinessAccountBioParams{
		BusinessConnectionID: businessConnectionID,
	}

	params.Option(opts...)

	_, err := ctx.client.SetBusinessAccountBio(params)

	return err
}

func (ctx *Context) SetBusinessAccountGiftSettings(
	businessConnectionID string,
	showGiftButton bool,
	acceptedGiftTypes AcceptedGiftTypes,
	opts ...SetBusinessAccountGiftSettingsOption,
) error {
	params := &SetBusinessAccountGiftSettingsParams{
		BusinessConnectionID: businessConnectionID,
		ShowGiftButton:       showGiftButton,
		AcceptedGiftTypes:    acceptedGiftTypes,
	}

	params.Option(opts...)

	_, err := ctx.client.SetBusinessAccountGiftSettings(params)

	return err
}

func (ctx *Context) SetBusinessAccountName(
	businessConnectionID string,
	firstName string,
	opts ...SetBusinessAccountNameOption,
) error {
	params := &SetBusinessAccountNameParams{
		BusinessConnectionID: businessConnectionID,
		FirstName:            firstName,
	}

	params.Option(opts...)

	_, err := ctx.client.SetBusinessAccountName(params)

	return err
}

func (ctx *Context) SetBusinessAccountProfilePhoto(
	businessConnectionID string,
	photo InputProfilePhoto,
	opts ...SetBusinessAccountProfilePhotoOption,
) error {
	params := &SetBusinessAccountProfilePhotoParams{
		BusinessConnectionID: businessConnectionID,
		Photo:                photo,
	}

	params.Option(opts...)

	_, err := ctx.client.SetBusinessAccountProfilePhoto(params)

	return err
}

func (ctx *Context) SetBusinessAccountUsername(
	businessConnectionID string,
	opts ...SetBusinessAccountUsernameOption,
) error {
	params := &SetBusinessAccountUsernameParams{
		BusinessConnectionID: businessConnectionID,
	}

	params.Option(opts...)

	_, err := ctx.client.SetBusinessAccountUsername(params)

	return err
}

func (ctx *Context) SetChatAdministratorCustomTitle(

	userID int64,
	customTitle string,
	opts ...SetChatAdministratorCustomTitleOption,
) error {
	params := &SetChatAdministratorCustomTitleParams{

		UserID:      userID,
		CustomTitle: customTitle,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SetChatAdministratorCustomTitle(params)

	return err
}

func (ctx *Context) SetChatDescription(

	opts ...SetChatDescriptionOption,
) error {
	params := &SetChatDescriptionParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SetChatDescription(params)

	return err
}

func (ctx *Context) SetChatMenuButton(
	opts ...SetChatMenuButtonOption,
) error {
	params := &SetChatMenuButtonParams{}

	params.Option(opts...)

	_, err := ctx.client.SetChatMenuButton(params)

	return err
}

func (ctx *Context) SetChatPermissions(

	permissions ChatPermissions,
	opts ...SetChatPermissionsOption,
) error {
	params := &SetChatPermissionsParams{

		Permissions: permissions,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SetChatPermissions(params)

	return err
}

func (ctx *Context) SetChatPhoto(

	photo InputFile,
	opts ...SetChatPhotoOption,
) error {
	params := &SetChatPhotoParams{

		Photo: photo,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SetChatPhoto(params)

	return err
}

func (ctx *Context) SetChatStickerSet(

	stickerSetName string,
	opts ...SetChatStickerSetOption,
) error {
	params := &SetChatStickerSetParams{

		StickerSetName: stickerSetName,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SetChatStickerSet(params)

	return err
}

func (ctx *Context) SetChatTitle(

	title string,
	opts ...SetChatTitleOption,
) error {
	params := &SetChatTitleParams{

		Title: title,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SetChatTitle(params)

	return err
}

func (ctx *Context) SetCustomEmojiStickerSetThumbnail(
	name string,
	opts ...SetCustomEmojiStickerSetThumbnailOption,
) error {
	params := &SetCustomEmojiStickerSetThumbnailParams{
		Name: name,
	}

	params.Option(opts...)

	_, err := ctx.client.SetCustomEmojiStickerSetThumbnail(params)

	return err
}

func (ctx *Context) SetGameScore(
	userID int64,
	score int64,
	opts ...SetGameScoreOption,
) error {
	params := &SetGameScoreParams{
		UserID: userID,
		Score:  score,
	}

	params.Option(opts...)

	_, err := ctx.client.SetGameScore(params)

	return err
}

func (ctx *Context) SetMessageReaction(

	messageID int64,
	opts ...SetMessageReactionOption,
) error {
	params := &SetMessageReactionParams{

		MessageID: messageID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.SetMessageReaction(params)

	return err
}

func (ctx *Context) SetMyCommands(
	commands []BotCommand,
	opts ...SetMyCommandsOption,
) error {
	params := &SetMyCommandsParams{
		Commands: commands,
	}

	params.Option(opts...)

	_, err := ctx.client.SetMyCommands(params)

	return err
}

func (ctx *Context) SetMyDefaultAdministratorRights(
	opts ...SetMyDefaultAdministratorRightsOption,
) error {
	params := &SetMyDefaultAdministratorRightsParams{}

	params.Option(opts...)

	_, err := ctx.client.SetMyDefaultAdministratorRights(params)

	return err
}

func (ctx *Context) SetMyDescription(
	opts ...SetMyDescriptionOption,
) error {
	params := &SetMyDescriptionParams{}

	params.Option(opts...)

	_, err := ctx.client.SetMyDescription(params)

	return err
}

func (ctx *Context) SetMyName(
	opts ...SetMyNameOption,
) error {
	params := &SetMyNameParams{}

	params.Option(opts...)

	_, err := ctx.client.SetMyName(params)

	return err
}

func (ctx *Context) SetMyProfilePhoto(
	photo InputProfilePhoto,
	opts ...SetMyProfilePhotoOption,
) error {
	params := &SetMyProfilePhotoParams{
		Photo: photo,
	}

	params.Option(opts...)

	_, err := ctx.client.SetMyProfilePhoto(params)

	return err
}

func (ctx *Context) SetMyShortDescription(
	opts ...SetMyShortDescriptionOption,
) error {
	params := &SetMyShortDescriptionParams{}

	params.Option(opts...)

	_, err := ctx.client.SetMyShortDescription(params)

	return err
}

func (ctx *Context) SetPassportDataErrors(
	userID int64,
	errors []PassportElementError,
	opts ...SetPassportDataErrorsOption,
) error {
	params := &SetPassportDataErrorsParams{
		UserID: userID,
		Errors: errors,
	}

	params.Option(opts...)

	_, err := ctx.client.SetPassportDataErrors(params)

	return err
}

func (ctx *Context) SetStickerEmojiList(
	sticker string,
	emojiList []string,
	opts ...SetStickerEmojiListOption,
) error {
	params := &SetStickerEmojiListParams{
		Sticker:   sticker,
		EmojiList: emojiList,
	}

	params.Option(opts...)

	_, err := ctx.client.SetStickerEmojiList(params)

	return err
}

func (ctx *Context) SetStickerKeywords(
	sticker string,
	opts ...SetStickerKeywordsOption,
) error {
	params := &SetStickerKeywordsParams{
		Sticker: sticker,
	}

	params.Option(opts...)

	_, err := ctx.client.SetStickerKeywords(params)

	return err
}

func (ctx *Context) SetStickerMaskPosition(
	sticker string,
	opts ...SetStickerMaskPositionOption,
) error {
	params := &SetStickerMaskPositionParams{
		Sticker: sticker,
	}

	params.Option(opts...)

	_, err := ctx.client.SetStickerMaskPosition(params)

	return err
}

func (ctx *Context) SetStickerPositionInSet(
	sticker string,
	position int64,
	opts ...SetStickerPositionInSetOption,
) error {
	params := &SetStickerPositionInSetParams{
		Sticker:  sticker,
		Position: position,
	}

	params.Option(opts...)

	_, err := ctx.client.SetStickerPositionInSet(params)

	return err
}

func (ctx *Context) SetStickerSetThumbnail(
	name string,
	userID int64,
	format string,
	opts ...SetStickerSetThumbnailOption,
) error {
	params := &SetStickerSetThumbnailParams{
		Name:   name,
		UserID: userID,
		Format: format,
	}

	params.Option(opts...)

	_, err := ctx.client.SetStickerSetThumbnail(params)

	return err
}

func (ctx *Context) SetStickerSetTitle(
	name string,
	title string,
	opts ...SetStickerSetTitleOption,
) error {
	params := &SetStickerSetTitleParams{
		Name:  name,
		Title: title,
	}

	params.Option(opts...)

	_, err := ctx.client.SetStickerSetTitle(params)

	return err
}

func (ctx *Context) SetUserEmojiStatus(
	userID int64,
	opts ...SetUserEmojiStatusOption,
) error {
	params := &SetUserEmojiStatusParams{
		UserID: userID,
	}

	params.Option(opts...)

	_, err := ctx.client.SetUserEmojiStatus(params)

	return err
}

func (ctx *Context) SetWebhook(
	uRL string,
	opts ...SetWebhookOption,
) error {
	params := &SetWebhookParams{
		URL: uRL,
	}

	params.Option(opts...)

	_, err := ctx.client.SetWebhook(params)

	return err
}

func (ctx *Context) StopMessageLiveLocation(

	opts ...StopMessageLiveLocationOption,
) error {
	params := &StopMessageLiveLocationParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.StopMessageLiveLocation(params)

	return err
}

func (ctx *Context) StopPoll(

	messageID int64,
	opts ...StopPollOption,
) error {
	params := &StopPollParams{

		MessageID: messageID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.StopPoll(params)

	return err
}

func (ctx *Context) TransferBusinessAccountStars(
	businessConnectionID string,
	starCount int64,
	opts ...TransferBusinessAccountStarsOption,
) error {
	params := &TransferBusinessAccountStarsParams{
		BusinessConnectionID: businessConnectionID,
		StarCount:            starCount,
	}

	params.Option(opts...)

	_, err := ctx.client.TransferBusinessAccountStars(params)

	return err
}

func (ctx *Context) TransferGift(
	businessConnectionID string,
	ownedGiftID string,
	newOwnerChatID int64,
	opts ...TransferGiftOption,
) error {
	params := &TransferGiftParams{
		BusinessConnectionID: businessConnectionID,
		OwnedGiftID:          ownedGiftID,
		NewOwnerChatID:       newOwnerChatID,
	}

	params.Option(opts...)

	_, err := ctx.client.TransferGift(params)

	return err
}

func (ctx *Context) UnbanChatMember(

	userID int64,
	opts ...UnbanChatMemberOption,
) error {
	params := &UnbanChatMemberParams{

		UserID: userID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.UnbanChatMember(params)

	return err
}

func (ctx *Context) UnbanChatSenderChat(

	senderChatID int64,
	opts ...UnbanChatSenderChatOption,
) error {
	params := &UnbanChatSenderChatParams{

		SenderChatID: senderChatID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.UnbanChatSenderChat(params)

	return err
}

func (ctx *Context) UnhideGeneralForumTopic(

	opts ...UnhideGeneralForumTopicOption,
) error {
	params := &UnhideGeneralForumTopicParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.UnhideGeneralForumTopic(params)

	return err
}

func (ctx *Context) UnpinAllChatMessages(

	opts ...UnpinAllChatMessagesOption,
) error {
	params := &UnpinAllChatMessagesParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.UnpinAllChatMessages(params)

	return err
}

func (ctx *Context) UnpinAllForumTopicMessages(

	messageThreadID int64,
	opts ...UnpinAllForumTopicMessagesOption,
) error {
	params := &UnpinAllForumTopicMessagesParams{

		MessageThreadID: messageThreadID,
	}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.UnpinAllForumTopicMessages(params)

	return err
}

func (ctx *Context) UnpinAllGeneralForumTopicMessages(

	opts ...UnpinAllGeneralForumTopicMessagesOption,
) error {
	params := &UnpinAllGeneralForumTopicMessagesParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.UnpinAllGeneralForumTopicMessages(params)

	return err
}

func (ctx *Context) UnpinChatMessage(

	opts ...UnpinChatMessageOption,
) error {
	params := &UnpinChatMessageParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.UnpinChatMessage(params)

	return err
}

func (ctx *Context) UpgradeGift(
	businessConnectionID string,
	ownedGiftID string,
	opts ...UpgradeGiftOption,
) error {
	params := &UpgradeGiftParams{
		BusinessConnectionID: businessConnectionID,
		OwnedGiftID:          ownedGiftID,
	}

	params.Option(opts...)

	_, err := ctx.client.UpgradeGift(params)

	return err
}

func (ctx *Context) UploadStickerFile(
	userID int64,
	sticker InputFile,
	stickerFormat string,
	opts ...UploadStickerFileOption,
) error {
	params := &UploadStickerFileParams{
		UserID:        userID,
		Sticker:       sticker,
		StickerFormat: stickerFormat,
	}

	params.Option(opts...)

	_, err := ctx.client.UploadStickerFile(params)

	return err
}

func (ctx *Context) VerifyChat(

	opts ...VerifyChatOption,
) error {
	params := &VerifyChatParams{}

	params.ChatID = ctx.ChatID()

	params.Option(opts...)

	_, err := ctx.client.VerifyChat(params)

	return err
}

func (ctx *Context) VerifyUser(
	userID int64,
	opts ...VerifyUserOption,
) error {
	params := &VerifyUserParams{
		UserID: userID,
	}

	params.Option(opts...)

	_, err := ctx.client.VerifyUser(params)

	return err
}

func defaultParseModeToInputMedia(media *InputMedia, parseMode string) {
	if media == nil {
		return
	}

	switch {

	case media.InputMediaAnimation != nil:
		if media.InputMediaAnimation.ParseMode == "" && len(media.InputMediaAnimation.CaptionEntities) == 0 {
			media.InputMediaAnimation.ParseMode = parseMode
		}

	case media.InputMediaDocument != nil:
		if media.InputMediaDocument.ParseMode == "" && len(media.InputMediaDocument.CaptionEntities) == 0 {
			media.InputMediaDocument.ParseMode = parseMode
		}

	case media.InputMediaAudio != nil:
		if media.InputMediaAudio.ParseMode == "" && len(media.InputMediaAudio.CaptionEntities) == 0 {
			media.InputMediaAudio.ParseMode = parseMode
		}

	case media.InputMediaPhoto != nil:
		if media.InputMediaPhoto.ParseMode == "" && len(media.InputMediaPhoto.CaptionEntities) == 0 {
			media.InputMediaPhoto.ParseMode = parseMode
		}

	case media.InputMediaVideo != nil:
		if media.InputMediaVideo.ParseMode == "" && len(media.InputMediaVideo.CaptionEntities) == 0 {
			media.InputMediaVideo.ParseMode = parseMode
		}
	}
}
