// Code generated by gogram/cmd/gen; DO NOT EDIT.

package gogram

type handleOn int

const (
	_ handleOn = iota
	handleOnMessage
	handleOnEditedMessage
	handleOnChannelPost
	handleOnEditedChannelPost
	handleOnBusinessConnection
	handleOnBusinessMessage
	handleOnEditedBusinessMessage
	handleOnDeletedBusinessMessages
	handleOnMessageReaction
	handleOnMessageReactionCount
	handleOnInlineQuery
	handleOnChosenInlineResult
	handleOnCallbackQuery
	handleOnShippingQuery
	handleOnPreCheckoutQuery
	handleOnPurchasedPaidMedia
	handleOnPoll
	handleOnPollAnswer
	handleOnMyChatMember
	handleOnChatMember
	handleOnChatJoinRequest
	handleOnChatBoost
	handleOnRemovedChatBoost
	handleOnCount
)

// HandleOnMessage registers a handler for updates containing Message.
func (rg *RouterGroup) HandleOnMessage(handler func(*Context, *Message) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnMessage] = append(rg.router.handlersOn[handleOnMessage], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().Message)
		}),
	})
}

// HandleOnEditedMessage registers a handler for updates containing EditedMessage.
func (rg *RouterGroup) HandleOnEditedMessage(handler func(*Context, *Message) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnEditedMessage] = append(rg.router.handlersOn[handleOnEditedMessage], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().EditedMessage)
		}),
	})
}

// HandleOnChannelPost registers a handler for updates containing ChannelPost.
func (rg *RouterGroup) HandleOnChannelPost(handler func(*Context, *Message) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnChannelPost] = append(rg.router.handlersOn[handleOnChannelPost], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().ChannelPost)
		}),
	})
}

// HandleOnEditedChannelPost registers a handler for updates containing EditedChannelPost.
func (rg *RouterGroup) HandleOnEditedChannelPost(handler func(*Context, *Message) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnEditedChannelPost] = append(rg.router.handlersOn[handleOnEditedChannelPost], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().EditedChannelPost)
		}),
	})
}

// HandleOnBusinessConnection registers a handler for updates containing BusinessConnection.
func (rg *RouterGroup) HandleOnBusinessConnection(handler func(*Context, *BusinessConnection) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnBusinessConnection] = append(rg.router.handlersOn[handleOnBusinessConnection], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().BusinessConnection)
		}),
	})
}

// HandleOnBusinessMessage registers a handler for updates containing BusinessMessage.
func (rg *RouterGroup) HandleOnBusinessMessage(handler func(*Context, *Message) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnBusinessMessage] = append(rg.router.handlersOn[handleOnBusinessMessage], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().BusinessMessage)
		}),
	})
}

// HandleOnEditedBusinessMessage registers a handler for updates containing EditedBusinessMessage.
func (rg *RouterGroup) HandleOnEditedBusinessMessage(handler func(*Context, *Message) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnEditedBusinessMessage] = append(rg.router.handlersOn[handleOnEditedBusinessMessage], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().EditedBusinessMessage)
		}),
	})
}

// HandleOnDeletedBusinessMessages registers a handler for updates containing DeletedBusinessMessages.
func (rg *RouterGroup) HandleOnDeletedBusinessMessages(handler func(*Context, *BusinessMessagesDeleted) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnDeletedBusinessMessages] = append(rg.router.handlersOn[handleOnDeletedBusinessMessages], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().DeletedBusinessMessages)
		}),
	})
}

// HandleOnMessageReaction registers a handler for updates containing MessageReaction.
func (rg *RouterGroup) HandleOnMessageReaction(handler func(*Context, *MessageReactionUpdated) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnMessageReaction] = append(rg.router.handlersOn[handleOnMessageReaction], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().MessageReaction)
		}),
	})
}

// HandleOnMessageReactionCount registers a handler for updates containing MessageReactionCount.
func (rg *RouterGroup) HandleOnMessageReactionCount(handler func(*Context, *MessageReactionCountUpdated) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnMessageReactionCount] = append(rg.router.handlersOn[handleOnMessageReactionCount], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().MessageReactionCount)
		}),
	})
}

// HandleOnInlineQuery registers a handler for updates containing InlineQuery.
func (rg *RouterGroup) HandleOnInlineQuery(handler func(*Context, *InlineQuery) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnInlineQuery] = append(rg.router.handlersOn[handleOnInlineQuery], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().InlineQuery)
		}),
	})
}

// HandleOnChosenInlineResult registers a handler for updates containing ChosenInlineResult.
func (rg *RouterGroup) HandleOnChosenInlineResult(handler func(*Context, *ChosenInlineResult) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnChosenInlineResult] = append(rg.router.handlersOn[handleOnChosenInlineResult], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().ChosenInlineResult)
		}),
	})
}

// HandleOnCallbackQuery registers a handler for updates containing CallbackQuery.
func (rg *RouterGroup) HandleOnCallbackQuery(handler func(*Context, *CallbackQuery) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnCallbackQuery] = append(rg.router.handlersOn[handleOnCallbackQuery], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().CallbackQuery)
		}),
	})
}

// HandleOnShippingQuery registers a handler for updates containing ShippingQuery.
func (rg *RouterGroup) HandleOnShippingQuery(handler func(*Context, *ShippingQuery) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnShippingQuery] = append(rg.router.handlersOn[handleOnShippingQuery], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().ShippingQuery)
		}),
	})
}

// HandleOnPreCheckoutQuery registers a handler for updates containing PreCheckoutQuery.
func (rg *RouterGroup) HandleOnPreCheckoutQuery(handler func(*Context, *PreCheckoutQuery) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnPreCheckoutQuery] = append(rg.router.handlersOn[handleOnPreCheckoutQuery], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().PreCheckoutQuery)
		}),
	})
}

// HandleOnPurchasedPaidMedia registers a handler for updates containing PurchasedPaidMedia.
func (rg *RouterGroup) HandleOnPurchasedPaidMedia(handler func(*Context, *PaidMediaPurchased) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnPurchasedPaidMedia] = append(rg.router.handlersOn[handleOnPurchasedPaidMedia], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().PurchasedPaidMedia)
		}),
	})
}

// HandleOnPoll registers a handler for updates containing Poll.
func (rg *RouterGroup) HandleOnPoll(handler func(*Context, *Poll) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnPoll] = append(rg.router.handlersOn[handleOnPoll], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().Poll)
		}),
	})
}

// HandleOnPollAnswer registers a handler for updates containing PollAnswer.
func (rg *RouterGroup) HandleOnPollAnswer(handler func(*Context, *PollAnswer) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnPollAnswer] = append(rg.router.handlersOn[handleOnPollAnswer], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().PollAnswer)
		}),
	})
}

// HandleOnMyChatMember registers a handler for updates containing MyChatMember.
func (rg *RouterGroup) HandleOnMyChatMember(handler func(*Context, *ChatMemberUpdated) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnMyChatMember] = append(rg.router.handlersOn[handleOnMyChatMember], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().MyChatMember)
		}),
	})
}

// HandleOnChatMember registers a handler for updates containing ChatMember.
func (rg *RouterGroup) HandleOnChatMember(handler func(*Context, *ChatMemberUpdated) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnChatMember] = append(rg.router.handlersOn[handleOnChatMember], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().ChatMember)
		}),
	})
}

// HandleOnChatJoinRequest registers a handler for updates containing ChatJoinRequest.
func (rg *RouterGroup) HandleOnChatJoinRequest(handler func(*Context, *ChatJoinRequest) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnChatJoinRequest] = append(rg.router.handlersOn[handleOnChatJoinRequest], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().ChatJoinRequest)
		}),
	})
}

// HandleOnChatBoost registers a handler for updates containing ChatBoost.
func (rg *RouterGroup) HandleOnChatBoost(handler func(*Context, *ChatBoostUpdated) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnChatBoost] = append(rg.router.handlersOn[handleOnChatBoost], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().ChatBoost)
		}),
	})
}

// HandleOnRemovedChatBoost registers a handler for updates containing RemovedChatBoost.
func (rg *RouterGroup) HandleOnRemovedChatBoost(handler func(*Context, *ChatBoostRemoved) error, filters ...Filter) {
	combined := func(ctx *Context) bool {
		if !rg.filter(ctx) {
			return false
		}
		for _, fn := range filters {
			if !fn(ctx) {
				return false
			}
		}
		return true
	}

	rg.router.handlersOn[handleOnRemovedChatBoost] = append(rg.router.handlersOn[handleOnRemovedChatBoost], route{
		filter: combined,
		handler: rg.applyMiddlewares(func(ctx *Context) error {
			return handler(ctx, ctx.Update().RemovedChatBoost)
		}),
	})
}
