// Code generated by gogram/cmd/gen; DO NOT EDIT.

package gogram

type handleOn int

const (
	_ handleOn = iota
	handleOnMessage
	handleOnEditedMessage
	handleOnChannelPost
	handleOnEditedChannelPost
	handleOnBusinessConnection
	handleOnBusinessMessage
	handleOnEditedBusinessMessage
	handleOnDeletedBusinessMessages
	handleOnMessageReaction
	handleOnMessageReactionCount
	handleOnInlineQuery
	handleOnChosenInlineResult
	handleOnCallbackQuery
	handleOnShippingQuery
	handleOnPreCheckoutQuery
	handleOnPurchasedPaidMedia
	handleOnPoll
	handleOnPollAnswer
	handleOnMyChatMember
	handleOnChatMember
	handleOnChatJoinRequest
	handleOnChatBoost
	handleOnRemovedChatBoost
	handleOnManagedBot
	handleOnCount
)

// HandleOnMessage registers a handler for updates containing Message.
func (rg *RouterGroup) HandleOnMessage(handler func(*Context, *Message) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().Message)
	}

	rg.handleOn(handleOnMessage, fn, filters...)
}

// HandleOnEditedMessage registers a handler for updates containing EditedMessage.
func (rg *RouterGroup) HandleOnEditedMessage(handler func(*Context, *Message) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().EditedMessage)
	}

	rg.handleOn(handleOnEditedMessage, fn, filters...)
}

// HandleOnChannelPost registers a handler for updates containing ChannelPost.
func (rg *RouterGroup) HandleOnChannelPost(handler func(*Context, *Message) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().ChannelPost)
	}

	rg.handleOn(handleOnChannelPost, fn, filters...)
}

// HandleOnEditedChannelPost registers a handler for updates containing EditedChannelPost.
func (rg *RouterGroup) HandleOnEditedChannelPost(handler func(*Context, *Message) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().EditedChannelPost)
	}

	rg.handleOn(handleOnEditedChannelPost, fn, filters...)
}

// HandleOnBusinessConnection registers a handler for updates containing BusinessConnection.
func (rg *RouterGroup) HandleOnBusinessConnection(handler func(*Context, *BusinessConnection) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().BusinessConnection)
	}

	rg.handleOn(handleOnBusinessConnection, fn, filters...)
}

// HandleOnBusinessMessage registers a handler for updates containing BusinessMessage.
func (rg *RouterGroup) HandleOnBusinessMessage(handler func(*Context, *Message) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().BusinessMessage)
	}

	rg.handleOn(handleOnBusinessMessage, fn, filters...)
}

// HandleOnEditedBusinessMessage registers a handler for updates containing EditedBusinessMessage.
func (rg *RouterGroup) HandleOnEditedBusinessMessage(handler func(*Context, *Message) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().EditedBusinessMessage)
	}

	rg.handleOn(handleOnEditedBusinessMessage, fn, filters...)
}

// HandleOnDeletedBusinessMessages registers a handler for updates containing DeletedBusinessMessages.
func (rg *RouterGroup) HandleOnDeletedBusinessMessages(handler func(*Context, *BusinessMessagesDeleted) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().DeletedBusinessMessages)
	}

	rg.handleOn(handleOnDeletedBusinessMessages, fn, filters...)
}

// HandleOnMessageReaction registers a handler for updates containing MessageReaction.
func (rg *RouterGroup) HandleOnMessageReaction(handler func(*Context, *MessageReactionUpdated) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().MessageReaction)
	}

	rg.handleOn(handleOnMessageReaction, fn, filters...)
}

// HandleOnMessageReactionCount registers a handler for updates containing MessageReactionCount.
func (rg *RouterGroup) HandleOnMessageReactionCount(handler func(*Context, *MessageReactionCountUpdated) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().MessageReactionCount)
	}

	rg.handleOn(handleOnMessageReactionCount, fn, filters...)
}

// HandleOnInlineQuery registers a handler for updates containing InlineQuery.
func (rg *RouterGroup) HandleOnInlineQuery(handler func(*Context, *InlineQuery) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().InlineQuery)
	}

	rg.handleOn(handleOnInlineQuery, fn, filters...)
}

// HandleOnChosenInlineResult registers a handler for updates containing ChosenInlineResult.
func (rg *RouterGroup) HandleOnChosenInlineResult(handler func(*Context, *ChosenInlineResult) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().ChosenInlineResult)
	}

	rg.handleOn(handleOnChosenInlineResult, fn, filters...)
}

// HandleOnCallbackQuery registers a handler for updates containing CallbackQuery.
func (rg *RouterGroup) HandleOnCallbackQuery(handler func(*Context, *CallbackQuery) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().CallbackQuery)
	}

	rg.handleOn(handleOnCallbackQuery, fn, filters...)
}

// HandleOnShippingQuery registers a handler for updates containing ShippingQuery.
func (rg *RouterGroup) HandleOnShippingQuery(handler func(*Context, *ShippingQuery) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().ShippingQuery)
	}

	rg.handleOn(handleOnShippingQuery, fn, filters...)
}

// HandleOnPreCheckoutQuery registers a handler for updates containing PreCheckoutQuery.
func (rg *RouterGroup) HandleOnPreCheckoutQuery(handler func(*Context, *PreCheckoutQuery) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().PreCheckoutQuery)
	}

	rg.handleOn(handleOnPreCheckoutQuery, fn, filters...)
}

// HandleOnPurchasedPaidMedia registers a handler for updates containing PurchasedPaidMedia.
func (rg *RouterGroup) HandleOnPurchasedPaidMedia(handler func(*Context, *PaidMediaPurchased) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().PurchasedPaidMedia)
	}

	rg.handleOn(handleOnPurchasedPaidMedia, fn, filters...)
}

// HandleOnPoll registers a handler for updates containing Poll.
func (rg *RouterGroup) HandleOnPoll(handler func(*Context, *Poll) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().Poll)
	}

	rg.handleOn(handleOnPoll, fn, filters...)
}

// HandleOnPollAnswer registers a handler for updates containing PollAnswer.
func (rg *RouterGroup) HandleOnPollAnswer(handler func(*Context, *PollAnswer) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().PollAnswer)
	}

	rg.handleOn(handleOnPollAnswer, fn, filters...)
}

// HandleOnMyChatMember registers a handler for updates containing MyChatMember.
func (rg *RouterGroup) HandleOnMyChatMember(handler func(*Context, *ChatMemberUpdated) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().MyChatMember)
	}

	rg.handleOn(handleOnMyChatMember, fn, filters...)
}

// HandleOnChatMember registers a handler for updates containing ChatMember.
func (rg *RouterGroup) HandleOnChatMember(handler func(*Context, *ChatMemberUpdated) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().ChatMember)
	}

	rg.handleOn(handleOnChatMember, fn, filters...)
}

// HandleOnChatJoinRequest registers a handler for updates containing ChatJoinRequest.
func (rg *RouterGroup) HandleOnChatJoinRequest(handler func(*Context, *ChatJoinRequest) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().ChatJoinRequest)
	}

	rg.handleOn(handleOnChatJoinRequest, fn, filters...)
}

// HandleOnChatBoost registers a handler for updates containing ChatBoost.
func (rg *RouterGroup) HandleOnChatBoost(handler func(*Context, *ChatBoostUpdated) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().ChatBoost)
	}

	rg.handleOn(handleOnChatBoost, fn, filters...)
}

// HandleOnRemovedChatBoost registers a handler for updates containing RemovedChatBoost.
func (rg *RouterGroup) HandleOnRemovedChatBoost(handler func(*Context, *ChatBoostRemoved) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().RemovedChatBoost)
	}

	rg.handleOn(handleOnRemovedChatBoost, fn, filters...)
}

// HandleOnManagedBot registers a handler for updates containing ManagedBot.
func (rg *RouterGroup) HandleOnManagedBot(handler func(*Context, *ManagedBotUpdated) error, filters ...Filter) {
	fn := func(ctx *Context) error {
		return handler(ctx, ctx.Update().ManagedBot)
	}

	rg.handleOn(handleOnManagedBot, fn, filters...)
}
